import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Button, Stack, Typography } from "@mui/material"
import routes from '../data/routes'
import Twitter from '../comps/Twitter'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UDOT Pics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Typography variant="h3" align='center'>Select a road to see the live camera feed.</Typography>
        <br />
        <Stack spacing={2}>
          {Object.entries(routes).map(x => (
            <Button key={x[0]} variant='contained' href={`/roads/${x[0]}/`}>{x[1].name}</Button>
          ))}
        </Stack>

        <br />
        <br />

        <Twitter />

        <br />
        <br />

        <Typography variant='h4'>
          About this Website
        </Typography>

        <Typography>
          <a href='https://udottraffic.utah.gov/'> https://udottraffic.utah.gov/ </a> 
          is the official site that shows all
          the traffic and road conditions in Utah. When the weather is bad,
          it can be comforting to take a quick look at the roads before heading out.
          Unfortunately, UDOT's website is absolutely not mobile friendly.
          So, I built this website. You can use this site to quickly check
          the road conditions on your phone. I have only mapped portions
          of I-15 and US-6, but I hope it will be of use.
        </Typography>

      </main>
    </>
  )
}


